### PR TITLE
feat: connected additional notes backend to frontend

### LINKED ISSUE #150: connect notes sections on log hours page to backend
When a shift is submitted on the log hours page, the notes section (if populated) should also be submitted to `notes` field in the shift schema.

### PR DESCRIPTION
**Pull request by joieng1**
Modified backend post route and frontend post request to include notes field.

### CODE REVIEW

**Review by ryanhu021 — CHANGES_REQUESTED** [review]
All the changes look good! There's one more thing that needs to be connected: the edit shift functions in the frontend and backend should also update the notes field

**Comment by joieng1** [comment]
I just connected the edit additional notes to the backend. However, when editing, the additional notes section is empty, regardless of whether there are or aren't notes in the shift object being rendered. I'm currently trying to work on getting this fixed.

**Comment by joieng1** [comment]
Just wanted to clarify, the commits in this pull request connect the additional notes backend to the frontend and fix three issues. Autofill notes now work when editing a shift (if notes are present). Additional notes are now shown in pastShifts section and in the thank you page after submitting a shift.

**Review by ryanhu021 — APPROVED** [review]
Looks great!

**Pull request merged**
