### PR TITLE
Password reset frontend

### LINKED ISSUE #10: Reset password component
### Description
make the frontend for the resetPassword component in the file: `resetPassword.tsx`  

this _may_ involve:
- using a form
- using a card
- some form validation
    -  all fields must be filled out
    - passwords must match

### Checklist

- [x] try to make it look like the [figma design](https://www.figma.com/file/kA6taQc7AAx0RtYiOSwKFH/The-Land-Conservancy?node-id=0%3A1)
- [x] must be responsive (looks good on mobile and with desktop resizing)
- [x] use [styled-components](https://styled-components.com/docs/api) for styling
- [x] basic form validation

### PR DESCRIPTION
**Pull request by bbmcmann**
Frontend component for password reset. I added really basic validation but can add more if needed. user is alerted with validation error if there is any. Don't have it setup to link between pages yet or anything but I can add that. Let me know if it needs any changes! : )

fixes #10

### CODE REVIEW

**Review by marissadarnell — APPROVED** [review]
The form components looks good. Just a note, make sure you add prettier to whatever editor you are using, (and also make sure it is enabled) or run the lint/ lint-fix scripts before pushing your code up. Feel free to fix the prettier issues sometime today, or I can also do it tomorrow when I start merging :) I also merged the react routing code if that was necessary to make your back button work, so you can also add that if you like. Otherwise, I'll address it this upcoming sprint.

**Comment by bbmcmann** [comment]
I can go ahead and try to make those changes over the next few days!

**Comment by bbmcmann** [comment]
I fixed the issues in prettier, once this one is merged with main I can go back in and add the linking for the router. Right now it's giving me a lot of trouble trying to merge with main and my branch so I can add the linking.

**Comment by marissadarnell** [comment]
Hi @bbmcmann , Thanks for fixing the prettier issues. I merged main into your branch, so you should be able to make changes without conflicts now 👍 . Let me know if you run into any more problems when doing the linking.

**Comment by bbmcmann** [comment]
Awesome thanks! new fixes are now pushed

**Comment by marissadarnell** [comment]
Nice, everything looks good. Merging now 👍

**Pull request merged**
