### PR TITLE
Uniform styles

### LINKED ISSUE #20: standardize styles
### Description
standardize some of the styles from previous week frontend tasks  
(authentication frontend components)

### Checklist

- [x] common styles -> into components/styledComponents file (e.g. button)
- [x] ~~all pages -> same validation method~~
- [x] dekstop: box, mobile: no box
- [x] ~~consider a theme? (ex. primary & secondary for buttons)~~
- [x] check all buttons nav to their places

### PR DESCRIPTION
**Pull request by marissadarnell**
pulled up common components / styles for auth pages  
closes #20

### CODE REVIEW

**Comment by marissadarnell** [comment]
@sfwathen @borajoo @Ritvik1121 @bbmcmann 

Hi everyone, I pulled _a lot_ of auth styling into an `authComponents.tsx` file, so all the pages generally have the same format. This will make it easier for people to work on these in the future without having to familiarize with 4 different code structures for all your pages.  

**Here are some things I would like each of you to check on your original page:**  
- [ ] test all the buttons / links go to the correct place
- [ ] pressing enter on the form does what is expected (may only submit if form is filled out correctly)
- [ ] make sure validation works (test the behavior in multiple situations)
- [ ] test responsiveness of the page
- [ ] feel free to look at other pages as well for bugs/ issues of any kind
- [ ] **then...** leave your review on this pull request (even if other people already have before you)

Please do let me know if you find anything wrong / I messed something up / I changed your code in a way that doesn't make sense :) or if you have general questions

**Comment by bbmcmann** [comment]
Looking over the reset password page I wrote as a part of authentication it looks all good

- back button brings me to correct page and submit logs to the console as it should right now
- hitting enter on the form also submits it only if it passes , as expected
- validation works for character length, the rest needs to be added (which I can do as part of next sprint if needed)
- the page is responsive, works better than what I originally had so it's really smooth now!
- **overall everything looks good to me and meets the design specs**

**Review by bbmcmann — COMMENTED** [review]
Looking over the reset password page I wrote as a part of authentication it looks all good

- back button brings me to correct page and submit logs to the console as it should right now
- hitting enter on the form also submits it only if it passes , as expected
- validation works for character length, the rest needs to be added (which I can do as part of next sprint if needed)
- the page is responsive, works better than what I originally had so it's really smooth now!
- **overall everything looks good to me and meets the design specs**

**Comment by borajoo** [comment]
I looked over the create account page, everything looks good! Link, validation, and submit works as intended, and it's responsive as well.

**Review by borajoo — COMMENTED** [review]
I looked over the create account page, everything looks good! Link, validation, and submit works as intended, and it's responsive as well.

**Review by Ritvik1121 — COMMENTED** [review]
Everything looks good with the forgot password component. The back arrow works as intended. The submit button also works as intended and the form validation is working as well.  The page is responsive and everything works.

**Pull request merged**
