### PR TITLE
Events from DB loaded into Events Page

### LINKED ISSUE #46: Load Events from the database
### Description
We have been using test data in memory up to his point. Now we want to load the collection from the database, most likely in `App.tsx` where we can pass the array of events as props to the pages that need it. 

this _may_ involve:
 - reviewing the backend to see how you should make the call on the frontend
 - making sure you can connect to MongoDB on your local machine (if you haven't yet)

### Checklist
- [ ] Load events from the database in `App.tsx`
- [ ] sort chronologically (by date)
- [ ] Pass to the `events.tsx` page
- [ ] edit `events.tsx` to use the database instead of data in memory
- [ ] test to see if it works/ shows up

### PR DESCRIPTION
**Pull request by bbmcmann**
Wrote fetch request in App.tsx
Had to update date conversion function because the mongoDB dates are ISO format. I had to add a lot of type definitions for stuff as well, I think I did it correctly based on the docs I've been going through, but if there is anything that needs to be fixed let me know! :)
closes #46

### CODE REVIEW

**Review by marissadarnell — CHANGES_REQUESTED** [review]
Hello hello @bbmcmann, nice job, this seems to load in the events correctly and display on the events page. However, it currently doesn't sort the events by date( newest are at the top and the oldest are at the bottom), or maybe I missed it somewhere, whoops.   
- [ ] Please let me know if/ when you'll be able to add that sorting function :)  

- [ ]  Also, if you can, I'm getting the unique key error for all the mapped Events , most likely because you are using the `event.id` rather than `event._id`. This will probably fix the unique key error and also give an eslint error for the `_id` dangling underscore. If you want, you can ignore eslint next line for that and I'll change the `.eslintrc` file to allow this once I merge. Or I can just complete this whole checkbox step, but I just wanted to let you know about it.

**Comment by bbmcmann** [comment]
Hey @marissadarnell that's my fault, I meant to go back and add the sorting and just totally forgot. I'll definitely go back in and add that, I can go fix the key error as well, seems like it won't be too difficult to fix. 
I have all of my finals and my final essays due on Monday, so I will most likely not be making any more pr's until after then. If it really needs to be done soon let me know and I can probably find time to do it, but otherwise I hope it's alright I wait a little bit.

**Comment by marissadarnell** [comment]
@bbmcmann You should be okay to wait until you are done with your assignments 👍  ; I'll let you know if anything changes though. Good luck on your finals!

**Comment by bbmcmann** [comment]
Hey Marissa, I just went in and fixed the two issues you pointed out. If there is anything else that needs to be tweaked, let me know and I can work on that!

**Review by marissadarnell — APPROVED** [review]
Okay, thanks for adding those few changes, this looks good :). 
The one thing I edited was having the newer events at the top instead of the bottom, but this is good to merge now

**Pull request merged**
